Vagrant::Config.run do |config|
  config.vm.box     = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define :foo do |foo_config|
  end

  config.vm.define :bar do |bar_config|
  end
end
