Vagrant::Config.run do |config|

  config.vm.define :ubuntu do |c|
    c.vm.box     = "Ubuntu 12.04"
    c.vm.box_url = "http://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box"
  end

  config.vm.define :centos do |c|
    c.vm.box = "CentOS 6.5"
    c.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"
  end
end
